### ISSUE TITLE
linking errors when using boost_programoptions

### ISSUE THREAD

**Issue by ghost** [conda-forge/boost-cpp-feedstock#21] opened 2018-03-05 20:41 UTC
I encountered [linker errors](https://stackoverflow.com/questions/27196312/boost-1-57-0-program-options-msvs-2013-linker-error) when linking to the shared version of the library on windows. Because `find_package()` automatically prefers the shared version, the shared libraries should be either fixed or removed on windows, and the static libraries should be renamed so that `find_package()` will find them.

**Comment by jakirkham** [comment] 2018-03-05 20:47
Could you please share the context this occurred? IOW what was being built, how was it being built, version of Boost used, Boost libraries involved, logs, etc.?

**Comment by xoviat** [comment] 2018-03-05 20:57
The linker error is the same as that encountered in the linked question. The reproducer is as follows:

CMakeLists.txt:

```
find_package(Boost REQUIRED COMPONENTS program_options)
add_library(test
test.cpp
)
target_link_libraries(test Boost::program_options)
```

**Comment by isuruf** [comment] 2018-03-05 22:44
full build log with `conda list` please

**Comment by jakirkham** [comment] 2022-04-09 00:50
Closing since there doesn't seem to be enough info to work with

**Closed by jakirkham** 2022-04-09 00:50 UTC
